### ISSUE TITLE
Cannot create a new user

### ISSUE THREAD

**Issue by ilyasrepo** [libbyk000/pocket-grocer#1]
Hi, as I was reviewing the project I could not create a new user and login to test out all the functionalities of the app. When navigating to https://pocket-grocer-403.azurewebsites.net/ and trying to create a new user, I get an error message "This username is already in use." I tried multiple usernames, that are most likely not to exist, and keep getting the error. Please let me know on slack if you resolve this issue so I can provide better feedback.

**Comment by lulup2** [comment]
I also experiences the same issue. I used a variety of very obscure usernames. All with the password "password." I then tried the login page to see if the error message was in fact an error, but could still not log in.

**Comment by libbyk000** [comment]
Hi! 
Thanks so much for opening this -- I'll msg you on Slack but also write back here. You need to be running the front end and back end **_both_** locally at the same time in order for the app to work. Our backend is not yet hosted so this is how the app works for now. This should fix your issue, but if not, let us know again here and we will continue to troubleshoot.

I've appended the developer guidelines to clarify this :) Thanks again!

**Comment by libbyk000** [comment]
Appears that this was the issue as Lulu was able to create an account!
